### ISSUE TITLE
Comparison - SMART和promethean底部是特殊的教育copy和CTA

### ISSUE THREAD

**Issue by Stan-Feng** [vibeus/vibe-website#424]
Live:
<img width="765" alt="image" src="https://user-images.githubusercontent.com/10073509/176103890-f4da4dd2-ef01-47bd-b5a0-85ff1dc94487.png">

Design:
<img width="397" alt="image" src="https://user-images.githubusercontent.com/10073509/176104509-81f9ee1e-9c2e-4b93-bc06-667b4ef25814.png">

https://www.figma.com/file/1J3LMfCqphiSx4fxbtGkcu/2022-new-website-wireframe?node-id=5578%3A95333

**Comment by Xeeeeiii** [comment]
Fixed in `release` branch
