### ISSUE TITLE
Order - "+"换行逻辑 应该放在行尾

### ISSUE THREAD

**Issue by Stan-Feng** [vibeus/vibe-website#434]
Context: https://vibeus.slack.com/archives/C0228PB7C8M/p1655797359038379

<img width="609" alt="image" src="https://user-images.githubusercontent.com/10073509/176134425-9e0f6df1-59ff-4d75-b739-0578547cd56b.png">

**Comment by dzr975336710** [comment]
FIX: e7f2ff0a7adaeb43c566802cc651aeaf39534ece
