### ISSUE TITLE
横向的滑动后，会跳转至某一固定页面

### ISSUE THREAD

**Issue by KaiShen1231** [vibeus/vibe-website#447]
地址：https://vibe-beta.com/solutions/health-care/ 

平台：pad-safari

操作步骤：
1. 滑动到user story 页面后
2. 横向滑动一下user story，看起来有的时候斜着划和竖着划也能触发
3. 页面会直接跳转到Cloud learning固定位置

现象：
23秒，30秒，50秒附近
https://user-images.githubusercontent.com/55375939/176415743-c5843d07-3814-45ed-bdfc-eab26159e096.mp4

预期：
能正常查看user story 和 往下滑动。

**Comment by dzr975336710** [comment]
鉴于ipad会来回出现导航栏，频繁触发resize，ipad版本以后都用静态版本。
这个页面已经改好了。
