### ISSUE TITLE
官网上的产品展示图整体细节很差，模糊有锯齿

### ISSUE THREAD

**Issue by KaiShen1231** [vibeus/vibe-website#458]
地址：vibe.us

平台：PC 27寸显示器

操作步骤：
浏览的时候注意图片的细节

现象：
![image](https://user-images.githubusercontent.com/55375939/177239741-10ca7fee-cbce-4e77-abb9-d756ddaa6bfe.png)
所有产品图都很模糊，边缘锯齿感非常严重，给用户的第一印象可能没有那么有质感。

预期：
图片的质感需要提升

**Comment by dzr975336710** [comment]
现在换图了应该还好，先close了。
