### ISSUE TITLE
smart cam 部分文字在滚动时会往下走

### ISSUE THREAD

**Issue by KaiShen1231** [vibeus/vibe-website#478]
地址：https://vibe-beta.com/

平台：Windows 27''

操作步骤：
https://www.loom.com/share/0e005e53020d404e850b2b002582ba1b

**Comment by dzr975336710** [comment]
@KaiShen1231 这个是周五晚上修改前吧，现在还有吗，没有我就close了。

**Comment by dzr975336710** [comment]
线上版本看了下没啥大问题，先close了。
